### ISSUE TITLE
unsupported protocol scheme

### ISSUE THREAD

**Issue by b3ni** [josmo/drone-google-chat#4]
I have a error in drone pipeline.

```
  - name: notification
    image: pelotech/drone-google-chat
    settings:
      webook: https://chat.googleapis.com/v1/spaces/XXXXXXXXXX/messages
      conversation_key: build_information
      key:
        from_secret: google_chat_key
      token:
        from_secret: google_chat_token
```

```
time="2022-11-08T17:36:13Z" level=fatal msg="Post /messages?key=******&token=******&threadKey=build_information: unsupported protocol scheme \"\""
```

Why is this error?
Thanks.

**Comment by josmo** [comment]
Hi @b3ni sorry I haven't looked at this project in a while - did you try quoting "https://chat.googleapis.com/v1/spaces/XXXXXXXXXX/messages" I'm wondering if the : and other characters are having a issue in the yaml file

**Comment by b3ni** [comment]
I solve it.

The example in the official documentation is wrong. https://plugins.drone.io/plugins/google-chat

webook: https://dynamite.sandbox.googleapis.com/v1/rooms/roomid

Its **webhook**

The final done yaml.

```
- name: notification
    image: pelotech/drone-google-chat
    settings:
      webhook: https://chat.googleapis.com/v1/spaces/XXXXXXXX
      conversation_key: build_information
      key:
        from_secret: google_chat_key
      token:
        from_secret: google_chat_token
```

Thanks
